### ISSUE TITLE
Quest 2 STL mount files

### ISSUE THREAD

**Issue by SummerSigh** [RedHawk989/EyeTrackVR-Hardware#2]
Please post STL (preferably STEP) for alpha quest 2 STL mount. (You can put a disclaimer that it isn't tested yet)

**Comment by RedHawk989** [comment]
Yes, I had to wait 24hours to upload to thingiverse (due to  license stuff I have to do it there) and today got dragged away from home. I'll be doing that later or tomorrow along with a GitHub page with links and info for it.

**Comment by RedHawk989** [comment]
https://www.thingiverse.com/thing:5400548 been posted here. I will add them to GitHub pages and stuff tomorrow or something. leaving the issue open until I do.

**Comment by RedHawk989** [comment]
https://redhawk989.github.io/EyeTrackVR/partslist/ done (btw im in the process of reformatting the stuff so its a mess)
