### ISSUE TITLE
Is there a supported model for Pico Neo 3 or Pico 4?

### ISSUE THREAD

**Issue by Ariakage** [RedHawk989/EyeTrackVR-Hardware#5]
Is there a supported model for Pico Neo 3 or Pico 4?Pico is a vr brand with affordable price. I hope you can support this brand and let more people use eye tracking.

**Comment by RedHawk989** [comment]
No one has created a mount yet. If you have the skills to make one and the ability to test it that would be helpful, otherwise you will have to wait until someone else gets around to it.

**Comment by Ariakage** [comment]
okay, thank you. I will try to make a model and share it later.
