### ISSUE TITLE
IR emitter seems dim

### ISSUE THREAD

**Issue by jellewie** [RedHawk989/EyeTrackVR-Hardware#6]
My LEDs seem to be too dark in the headset for use, and when taking a photo (Your phone camera can also see the light) they are super dim (see pic below). Am I doing something wrong here, or is an instruction to vague or something?

![image](https://user-images.githubusercontent.com/1545223/233777456-a03195c6-5db9-4801-bba6-1d4c530e3dad.png)
(Don't mind all the super glue...)

# My Setup
And the recommended from LCSC LED (C965891)
https://www.lcsc.com/product-detail/_XINGLIGHT-_C965891.html

I use the 357Ohm resistor (C60238)
https://www.lcsc.com/product-detail/_UNI-ROYAL-Uniroyal-Elec-_C60238.html
(I also have the 348Ohm one if you want me to try that, but I think that would make little difference)

The way the boards are configured (the recommended way): 
![image](https://user-images.githubusercontent.com/1545223/233776968-dcd5cbb6-c97b-4444-82f2-a72e62982507.png)

Measured the voltage to the LEDs, which is 5,01V which should be very fine:
![image](https://user-images.githubusercontent.com/1545223/233777527-97c97094-0cc3-401d-8f6c-6d59fa87a9b0.png)

**Comment by RedHawk989** [comment]
Can you show me a pic of what it looks like in-headset? your cameras might have their IR filters on.

**Comment by jellewie** [comment]
Used a different camera (Oneplus, instead of Pixel) and that seems to be better:
![image](https://user-images.githubusercontent.com/1545223/235353140-3fe1994a-0fb2-445f-bf7b-d4e2f71622d8.png)

but it is still completely black on the camera's:
![image](https://user-images.githubusercontent.com/1545223/235353052-849629db-d866-4976-8e19-42e0c09a5f6a.png)

I rechecked the schematic, and it is right like this:
![image](https://user-images.githubusercontent.com/1545223/235353263-2c8d2504-85fb-49ab-ae17-a2e4c09898f1.png)

**Comment by RedHawk989** [comment]
Then your cameras have IR filters on. https://www.youtube.com/watch?v=QYH-FWvDbDc

**Comment by jellewie** [comment]
This was the problem, this info should be (at least hinted to) in the docs imo.

Also while putting it back one was unsharp, a note about focus length would also be a good addition.
