### ISSUE TITLE
missing SCH file and boards are not complete

### ISSUE THREAD

**Issue by Shade-emry** [RedHawk989/EyeTrackVR-Hardware#8]
*.sch files are missing for the current version boards and the PCB design for both it and mainboard looks to have been made for a batch order and is incomplete. Without the SCH files optimizing this board will take forever if it is even possible.

![Board 1](https://github.com/EyeTrackVR/EyeTrackVR-Hardware/assets/156789960/2d32b10f-430f-4f12-88d2-5aa36e58277f)

**Comment by Shade-emry** [comment]
![Board 2](https://github.com/EyeTrackVR/EyeTrackVR-Hardware/assets/156789960/d2cd7da7-2b7e-4d17-8a0a-6029462b602a)

**Comment by NanashiTheNameless** [comment]
Can confirm, its really either a really bad oversight or a deliberate attempt to force users to buy theirs instead of having it just made overseas.

My intuition is leading towards the second given the way most larger "hobbyist projects" have gone lately...

**Comment by RedHawk989** [comment]
Im not sure what you mean? They are panalized to meet the minimum size for PCBA. They don't appear correct in the previews, but all mainstream fabs support the given format (and will "fix" them during production)

**Comment by RedHawk989** [comment]
>Can confirm, its really either a really bad oversight or a deliberate attempt to force users to buy theirs instead of having it just made overseas.
>
> My intuition is leading towards the second given the way most larger "hobbyist projects" have gone lately...

This is a sad take. It's easier on me when people buy their own and I don’t do this project for the money. I just want to see the project succeed and provide value.

**Comment by Shade-emry** [comment]
Ahh, alright. I can confirm that JLCPCB will automatically fix it. This matter can be closed. My apologies for raising an issue about it

**Comment by Shade-emry** [comment]
they will also accept a Schim as a pdf. A big oversight on my part, thank you.

**Comment by Shade-emry** [comment]
Great job with this by the way!
